#ifndef MENUSTATES_H
#define MENUSTATES_H

enum MenuState { DEFAULTSTATE, OVERVIEWSTATE, BUILDSTATE, ACTION, RESET, INVENTORY, PLACINGBUILDING, PLACINGBUILDINGTEST, BUILDINGINFOSTATE, 
	PRODUCTIONSTATE, ENTITYINFOSTATE };


#endif 
